[build]
  functions = "./functions"
  publish = "./public"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"